# src/main/resources/application.yml
kwai:
  base-url: https://openapi.kwaixiaodian.com
  app-key: "ks697213520049866660"
  app-secret: "zyNK73fVyCio7lLCnG6cKw"
  sign-secret: "c8f7e28978c5f0415e238466f89da0f2"
  shops:
    shop-biaowangchangjia:
      access-token: "ChFvYXV0aC5hY2Nlc3NUb2tlbhJAM4ClLInqB-ESR7T0XKr0DGMJ_yuHS3_56cOS1NlBbPqVz-BokZ2_X_T3UvyZXlYpGu9eRo0sgg6opV8-J05YLRoSXmId3s_9TpqnCS4FlyiXkIhhIiAS13T2SWxHL9zv_L26Suv2KM6ZhM8wT3jQPehS7w-Q_ygFMAE"
    shop-biaowanggongchang:
      access-token: "ChFvYXV0aC5hY2Nlc3NUb2tlbhJAVcfbzJYZSaI33AV1LUqWhOiyhXkKL0tCAgcz6pGEol30XJC1PGEN2MGysNV7GoTGEPx-Z-Olu0ChzazuiEDNshoSj7CN238WSuq-kBNyCQnaCfBmIiC3qUXRvtt3-ihtvK1CGDgqnzxAecz7zvhDhwC9QfftKCgFMAE"

  time:
    zone: Asia/Shanghai
    lookback-days: 7

spring:
  mongodb:
    uri: mongodb://localhost:27017/ERP
    auto-index-creation: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

