# src/main/resources/application.yml
kwai:
  base-url: https://openapi.kwaixiaodian.com
  app-key: "ks670191920826361315"
  app-secret: "CO1TpCII8ydUJXd1DcppFA"
  sign-secret: "b0f7478aa6d1699838b2416618fa01b5"
  shops:
    shop-biaowanggongchang:
      access-token: "ChFvYXV0aC5hY2Nlc3NUb2tlbhJwx_mHzNeOiLOWaaM6FplYGPLbF8x9VcHPtL0cAWLDu1cTOrJdmzeQPCcGnzm4alhODkV3uMQVUn6IeHZ7OBLl0kX49aFeAZNKn-3xpfe1Fy9lxbEpYP7WUBfdt1nKtk9-HuJQeZtHiE7y_Uhtag1FHBoSXmId3s_9TpqnCS4FlyiXkIhhIiATfy4MG3fvx59Y060CdFY1hTZ5l6jHPH_wTSm8h0MmPygFMAE"
      refresh-token: "ChJvYXV0aC5yZWZyZXNoVG9rZW4SwAH2fghEq2p1leeaCP0CLTJn5uKtN0TMk_h-hiArVFQWH3HkcU9DVP2AY8LeAfqo76svy9wQUvacFg1AvZoP1ehPy5e8oXso-Q7N9RY7p9kfqLWekxzoM7LW4TdsMhBRQWH-JxK3vUPnDLuo76p0_DdCc_oXDXqF7USZcx4ioNjiaHDi9xXcxqKM9Sc7eQ1hk513eaf8dSc9qAarnRDzAv7dNs4Gj29IxfMHLihDkZa7k29xDM6UCja2pqxphyOmjZEaEgxisP4G5Stsq8OygUO1ISR9CiIgLpj2cVf1ufqd7BD-eMJGfWdZmq4lY4hTpveLT0Rqb7woBTAB"
    shop-niurenlonggezhongkebiaowang:
      access-token: "ChFvYXV0aC5hY2Nlc3NUb2tlbhJwZylVhbSIXZB6jSHS9fgJFYApEE7c7lPdEkN4wIzy1m2P-tAw2k3MCFOnj0w8clpJPijOqSI057UFWjabb4LOz0w8hcksp0Mdv4SqG2fKMhLbaJHzbORizzYm2GKSWO95IIC-UZ_nQPm4_pr779SJUhoSIEH75Kg-RaqlrUNstFhsUg4wIiCS8Thr02NoujziFle111JoUksJ43x3GvX4VTRaCc2PDigFMAE"
      refresh-token: "ChJvYXV0aC5yZWZyZXNoVG9rZW4SsAG20YnC_UBPixmyW1Le0j0FJR1hDCd5crHdgbNTZqhmkLn5GKov3ou4uWgVcJhlWDXCXvhmB7gEjuwWrd6pflPf3Rf4r7PHU9qgtstiz_lf3wLxaTFsZEOZs_Nx85dsCeQHrHJ8ZVq6KBURaGoCk5XCDmtibRnGyzgNRWazbBWZL_IXdEfEj1KrVt3TSBxDYO9ua2GMmyeEFbYBu-1JYnbHDJd_b0vSUmTS2wFWYEis1xoS7OjQLYo8-xC8vIrzi2NrqPdYIiBPvREcUxOusMcKf8Vlo1dXLI6b1_3s-VfyibvLgx81qygFMAE"
    shop-yuganyouchangjia:
      access-token: "ChFvYXV0aC5hY2Nlc3NUb2tlbhJwirAHEggbAN2raZAlBxnvkjb5jDAtC4vfZlI8tG8h1aSceT4cSigSKIqXan1yjBn6iNCQEokb85Z2FDcu1Aj-yJVh4FyV035TanCoZySGgADret-Uyg2tHGcK4rsuRgp0AP8P98rlOFAr7sLdYehmZRoSLXYcsLhiRIaIobX-VUCKIblrIiDKUbQJI5ahPrWbwZs8t0AZtSW-v50vYAID-aCAi7x_GSgFMAE"
      refresh-token: "ChJvYXV0aC5yZWZyZXNoVG9rZW4SsAEeT7ntBHNEQKBTsdbi6Eu2HJFzFdFntNKDI34UKFgGWUDzwoMaAyv_r6myeKnuWa271XiKWPGF1Cq4Qm0dpofxFCrphNjtVtDUd9wc-PtMXTshWPvYqDxiidM-q80Uf3L8CanGbRW8TMOeqtCA4wQUe9zrli097G-A-VNCrFUzzde03XCsl48H9WdtudeKat-u5iE-OqJg3YNPcZN8OBbIhZbOG3OZF_e_t6jtYMnuMRoST2oMjTPL5BVa1rCYPDy19BwpIiDGjU2VWrDMfETknhWlGw8m6axXJHl4YKQB7M6r3uM6lCgFMAE"
    shop-duniukuaizhangchangjia:
      access-token: "ChFvYXV0aC5hY2Nlc3NUb2tlbhJw21_1JQ9b3C3N0iWbBdiH13l8K-t1uDhPrphI214BCradIGn8p5wCKgyDeeztLof7nwyWbjdZ-3rOxovQw5fOP5nBHOhjbcQQbPZCFin78Mnq6zcB3Sc7Lc9QJ21nJ4x2xojf-TBSM1IfScjE8_qgKhoSj7CN238WSuq-kBNyCQnaCfBmIiDC4W3MUBQsLebfOdJF3S4a8KtqlfoQb9noIoUb8qxdxigFMAE"
      refresh-token: "ChJvYXV0aC5yZWZyZXNoVG9rZW4SsAGn-zz2eW7TCQVlo8P3KCdSjSbjqgC54Y5svho4nD4Z26-4hNgO7JGMX06TGpl66WP1H4U7ypTnOt3n70OzZfKEE8OhfqENgmknFKfKf03XQ-pJGzIVeyCGro4WPEla2cDEioZsVGgFNC-Jr3IFtEsUEhJ8CVh-FCHazFWgrl2tvOLk39xVYNF-2iSXMVkwZy0_7o31_dO1qhz3-SIY4WrZZthQl8_QyQllnK67Ojb2MxoSnljOmCdLtHWjuSnDd58__CFjIiAJPzZKjrRTiIMNn2DBaK72EEjQpehXGUPVKP3o6IEZrSgFMAE"
    shop-zixidapaodangongchang:
      access-token: "ChFvYXV0aC5hY2Nlc3NUb2tlbhJw-TWO78vs72xpdB3xuD92x_mO0_tLI9QjFGSCyPE7Td39bgl5hnWa2uI2sCemfq8_nUQowy3RLYbOOAL_2Wi8Ctu5QFGwERb0TS1joMZ4gG3Zvpvwl-_hTXHCtx2uv29zrqJkeyesyib3L3CU37Xc1xoSOYuaoIMQQbq8-XpVu7XiJ6dNIiBlgo0ojj5mh-JFZvg72gNceQ3gSO-wI9X-FmDmYmtIJigFMAE"
      refresh-token: "ChFvYXV0aC5hY2Nlc3NUb2tlbhJw-TWO78vs72xpdB3xuD92x_mO0_tLI9QjFGSCyPE7Td39bgl5hnWa2uI2sCemfq8_nUQowy3RLYbOOAL_2Wi8Ctu5QFGwERb0TS1joMZ4gG3Zvpvwl-_hTXHCtx2uv29zrqJkeyesyib3L3CU37Xc1xoSOYuaoIMQQbq8-XpVu7XiJ6dNIiBlgo0ojj5mh-JFZvg72gNceQ3gSO-wI9X-FmDmYmtIJigFMAE"
    shop-duniukuaizhangchangjiapifa:
      access-token: "ChFvYXV0aC5hY2Nlc3NUb2tlbhJw3_IuMu6VDv4Hi5deyIuhdN-L6xYm6HuJfpBT-IvPeRPK24n3qB8aKfEUTn4wm6ooTaRCIamoAy7vMVZGU1vYOSBmaaRV3E4aERCapr0oKy_9qghl-yDG8qLX9jQhSrHI82kYL0zZoL9f8cJ9uHSjpxoSYfZ9co1oSiGh93iNTWvF5WYVIiDPhKPFB6XsaMnrexi65znjK0nAD9ZEM1a1FIsFioaaAygFMAE"
      refresh-token: "ChJvYXV0aC5yZWZyZXNoVG9rZW4SsAGGMDik02IPuxvHq4IM3Oz8Xg6sZmi_imm5sIabLGHmijUIVfB-VMbbMsqxSZ7fFAKN6hX_arzaWVhFRpijH0ND5nbc93Kn2EA859n-jMSc23cvyNuqfatMiHG91dcW_ZXy6Tmn4OopYtvnoVFyPhgSLG8GuSoEchlq1Wx1MTQkb5B6jSLSJC1J7q1Pd394Ny_6Qec6FY54wNWgv1TuGV0qi8kKkvEOciLjtfaSzT94WBoShN_B9N0ccXe88WX11P1sxV7dIiA1KwlPBoN-3n8rgvZ3tmBNsXC1r_tO084SDs0zDvsTQigFMAE"
    shop-biaowanghuojuntaigongcheng:
      access-token: "ChFvYXV0aC5hY2Nlc3NUb2tlbhJw0mi55mtMI47UgAxcSgeF32_Boj788QK7y5mMJr0z4iinnBZXIm2O4y8nmqlkKow_9jjmu9yCl4Sqvz5EbyS5ASMjf4PTNP9VDsLuZHULbJelNef-9PVewN_3PbmBILXjCZbGrF0nVYobFqj8ZrmHaxoSYfZ9co1oSiGh93iNTWvF5WYVIiCTapOhvk4EEdH6Gx848awqKRB8SdUALl9v9sizoGqN6SgFMAE"
      refresh-token: "ChJvYXV0aC5yZWZyZXNoVG9rZW4SsAE2UB1Y1HZiGUjWjhRY-rGjmEcvMadhwuZNPBbX4ryqHDrLGrCx2rWCzKfZPNoWiEzRj9gWyjA-xctfJ0aFFQfakMztwCs174TT4gh5cxjmym1Y5Wj4W6xwqZ06W2amXhxhJQGsgXwwVPudnu4r9zNggEbNo0d17Yrj_kPdvq4aPX9HsoONtaP6ayS9MjuC8NG5cN0tBE3_aTR7AHl4M9o7FrpUIS78tIaiY9bDWxpIihoSYea4eoHshahNmq7k-U8GgXUrIiAEPY8250XQkemuAxM6oOJSstjjH6AAkoC7ut05ZCusSigFMAE"
    shop-quanchongqinggongchang:
      access-token: "ChFvYXV0aC5hY2Nlc3NUb2tlbhJwKplJV-9IRuvEvCEmCQiLRQXxz3u12aITmiJzNEbGn7nSBDrzwEd5sNNNqXmasLtXzBeDgxgQfMcVk3TG_Lx2JLu4wxtkPO6tOX7NMUDtzVzCLXeYa9KKD0kLvPEuGe2wA7fJexr_t8CRmSwJimiLfBoSIEH75Kg-RaqlrUNstFhsUg4wIiCDm6Ttp4CE-FbVEJ3X01QqV36SgVG0n5ljAscWnrIsVygFMAE"
      refresh-token: "ChJvYXV0aC5yZWZyZXNoVG9rZW4SsAGef-5PX-eyyNh7U2ZdmOz1v_VBO8kR8Q52puRms8-X23IT3CH5vT2vqrRYGn0qTSqfse0_fli3UYOydMl6kTs7ef7yj1G82l_-Ps-ZnJL27nqUmn_faHK0-jq6twfUv0speJm39-xIdgtoO7-tzUSKr7gGS1DiN4zhBIKro8gTP5Tfaoqbveps9fEKpMtfdMvdc16KfAOr7Z-Rq3SVoF51S9R9lsKJnxMswSnJga793xoSlmyWc__isA0ZraLhGGGITvNMIiD9rPqDM8F8yqdB9kiyLhui3F4HpEr7xqJMWZfHSnyqESgFMAE"



  time:
    zone: Asia/Shanghai
    lookback-days: 7



spring:
  mongodb:
    uri: mongodb://localhost:27018/ERP
    auto-index-creation: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

